name: favorite_places
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  image_picker: ^1.2.0
  location: ^8.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  uuid: ^4.5.2
  very_good_analysis: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
